import { Pose } from "../utils/Pose"

const Variations = {
	chair: [3, 36], // ["Chair", "Revolved Chair"],
	childs: [4, 13], // ["Child's", "Extended Child's"],
	downwardDog: [11, 12], // ["Downward Dog", "Three-legged Downward Dog"],
	forearmBalance: [16], // ["Forearm Balance"], //, "Scorpion"],
	handstand: [22, 23, 38], // ["Handstand", "Handstand Splits", "Scorpion Handstand"],
	invertedStaff: [24, 30], // ["Inverted Staff", "One-legged Inverted Staff"],
	locust: [25, 26], // ["Locust I", "Locust III"],
	pigeon: [19, 31, 29], // ["Half Pigeon", "One-legged King Pigeon", "Mermaid"],
	plank: [32, 17], // ["Plank", "Forearm Plank"],
	sideAngle: [15, 37], // ["Extended Side Angle", "Revolved Side Angle"],
	standingForwardBend: [45, 46, 21], // ["Standing Forward Bend", "Standing Forward Bend with Raised Arms", "Half Standing Forward Bend"],
	warrior: [51, 52, 53], // ["Warrior I", "Warrior II", "Warrior III"],
	wideLeggedBend: [74, 75], // ["Wide-legged Bend I", "Wide-legged Bend III"],
}

const Poses = [
	new Pose("Bridge", require("../assets/poses/BridgePose.png"), "Intermediate", "Supine", "Back Bend", "10"),
	new Pose("Butterfly", require("../assets/poses/ButterflyPose.png"), "Beginner", "Seated", "Neutral", "10"),
	new Pose("Cat", require("../assets/poses/CatPose.png"), "Beginner", "Supported", "Forward Bend", "10"),
	new Pose("Chair", require("../assets/poses/ChairPose.png"), "Beginner", "Standing", "Balance", "10", Variations.chair),
	new Pose("Child's", require("../assets/poses/ChildsPose.png"), "Beginner", "Prone", "Forward Bend", "10", Variations.childs),
	new Pose("Cobra", require("../assets/poses/CobraPose.png"), "Intermediate", "Prone", "Back Bend", "10"),
	new Pose("Corpse", require("../assets/poses/CorpsePose.png"), "Beginner", "Supine", "Neutral", "10"),
	new Pose("Cow", require("../assets/poses/CowPose.png"), "Beginner", "Supported", "Back Bend", "10"),
	new Pose("Crescent Lunge on Knee", require("../assets/poses/CrescentLungeKneePose.png"), "Beginner", "Standing", "Neutral", "10"),
	new Pose("Crow", require("../assets/poses/CrowPose.png"), "Intermediate", "Arm Balance", "Balance", "10"),
	new Pose("Lord of the Dance", require("../assets/poses/DancersPose.png"), "Advanced", "Standing", "Balance", "10"),
	new Pose("Downward Dog", require("../assets/poses/DownwardDogPose.png"), "Beginner", "Supported", "Forward Bend", "10", Variations.downwardDog),
	new Pose("Three-legged Downward Dog", require("../assets/poses/DownwardDogThreeLeggedPose.png"), "Intermediate", "Supported", "Balance", "10", Variations.downwardDog),
	new Pose("Extended Child's", require("../assets/poses/ExtendedChildsPose.png"), "Beginner", "Prone", "Forward Bend", "10", Variations.childs),
	new Pose("Extended Puppy", require("../assets/poses/ExtendedPuppyPose.png"), "Intermediate", "Prone", "Back Bend", "10"),
	new Pose("Extended Side Angle", require("../assets/poses/ExtendedSideAnglePose.png"), "Intermediate", "Standing", "Lateral Bend", "10", Variations.sideAngle),
	new Pose("Forearm Balance", require("../assets/poses/ForearmBalancePose.png"), "Advanced", "Arm Balance", "Balance", "10", Variations.forearmBalance),
	new Pose("Forearm Plank", require("../assets/poses/ForearmPlankPose.png"), "Intermediate", "10", "Supported", "Balance", Variations.plank),
	new Pose("Half Moon", require("../assets/poses/HalfMoonPose.png"), "Intermediate", "Standing", "Balance", "10"),
	new Pose("Half Pigeon", require("../assets/poses/HalfPigeonPose.png"), "Beginner", "Seated", "Back Bend", "10", Variations.pigeon),
	new Pose("Half Splits", require("../assets/poses/HalfSplitsPose.png"), "Intermediate", "Supported", "Forward Bend", "10"),
	new Pose("Half Standing Forward Bend", require("../assets/poses/HalfStandingForwardBendPose.png"), "Beginner", "Standing", "Forward Bend", "10", Variations.standingForwardBend),
	new Pose("Handstand", require("../assets/poses/HandstandPose.png"), "Advanced", "Arm Balance", "Balance", "10", Variations.handstand),
	new Pose("Handstand Splits", require("../assets/poses/HandstandSplitsPose.png"), "Advanced", "Arm Balance", "Balance", "10", Variations.handstand),
	new Pose("Inverted Staff", require("../assets/poses/InvertedStaffPose.png"), "Advanced", "Supported", "Back Bend", "10", Variations.invertedStaff),
	new Pose("Locust I", require("../assets/poses/LocustPose.png"), "Intermediate", "Supine", "Back Bend", "10", Variations.locust),
	new Pose("Locust III", require("../assets/poses/LocustCPose.png"), "Intermediate", "Supine", "Back Bend", "10", Variations.locust),
	new Pose("Lotus", require("../assets/poses/LotusPose.png"), "Intermediate", "Seated", "Neutral", "10"),
	new Pose("Lunge on Knee", require("../assets/poses/LungeKneePose.png"), "Beginner", "Supported", "Balance", "10"),
	new Pose("Mermaid", require("../assets/poses/MermaidPose.png"), "Intermediate", "Seated", "Back Bend", "10", Variations.pigeon),
	new Pose("One-legged Inverted Staff", require("../assets/poses/OneLeggedInvertedStaffPose.png"), "Advanced", "Supported", "Back Bend", "10", Variations.invertedStaff),
	new Pose("One-legged King Pigeon", require("../assets/poses/OneLeggedKingPigeonPose.png"), "Advanced", "Seated", "Back Bend", "10", Variations.pigeon),
	new Pose("Plank", require("../assets/poses/PlankPose.png"), "Intermediate", "Supported", "Balance", "10", Variations.plank),
	new Pose("Plow", require("../assets/poses/PlowPose.png"), "Intermediate", "Arm Balance", "Forward Bend", "10"),
	new Pose("Reclined Big Toe", require("../assets/poses/ReclinedBigToePose.png"), "Intermediate", "Supine", "Neutral", "10"),
	new Pose("Reclined Spinal Twist", require("../assets/poses/ReclinedSpinalTwistPose.png"), "Beginner", "Supine", "Twist", "10"),
	new Pose("Revolved Chair", require("../assets/poses/RevolvedChairPose.png"), "Beginner", "Standing", "Twist", "10", Variations.chair),
	new Pose("Revolved Side Angle", require("../assets/poses/RevolvedSideAnglePose.png"), "Intermediate", "Standing", "Twist", "10", Variations.sideAngle),
	new Pose("Scorpion Handstand", require("../assets/poses/ScorpionHandstandPose.png"), "Advanced", "Arm Balance", "Back Bend", "10", Variations.handstand),
	new Pose("Seated Camel", require("../assets/poses/SeatedCamelPose.png"), "Intermediate", "Seated", "Back Bend", "10"),
	new Pose("Seated Forward Bend", require("../assets/poses/SeatedForwardBendPose.png"), "Beginner", "Seated", "Forward Bend", "10"),
	new Pose("Seated Spinal Twist", require("../assets/poses/SeatedSpinalTwistPose.png"), "Intermediate", "Seated", "Twist", "10"),
	new Pose("Supported Shoulderstand", require("../assets/poses/SupportedShoulderstandPose.png"), "Intermediate", "Arm Balance", "Balance", "10"),
	new Pose("Side Forearm Plank", require("../assets/poses/SideForearmPlankPose.png"), "Intermediate", "Supported", "Balance", "10"),
	new Pose("Sphinx", require("../assets/poses/SphinxPose.png"), "Beginner", "Supine", "Back Bend", "10"),
	new Pose("Standing Forward Bend", require("../assets/poses/StandingForwardBendPose.png"), "Beginner", "Standing", "Forward Bend", "10", Variations.standingForwardBend),
	new Pose("Standing Forward Bend with Raised Arms", require("../assets/poses/StandingForwardBend2Pose.png"), "Intermediate", "Standing", "Forward Bend", "10", Variations.standingForwardBend),
	new Pose("Supported Sage Visvamitras", require("../assets/poses/SupportedSageVisvamitrasPose.png"), "Advanced", "Supported", "Balance", "10"),
	new Pose("Tree", require("../assets/poses/TreePose.png"), "Intermediate", "Standing", "Balance", "10"),
	new Pose("Triangle", require("../assets/poses/TrianglePose.png"), "Beginner", "Standing", "Lateral Bend", "10"),
	new Pose("Upward Plank", require("../assets/poses/UpwardPlankPose.png"), "Beginner", "Supported", "Back Bend", "10"),
	new Pose("Warrior I", require("../assets/poses/WarriorAPose.png"), "Beginner", "Standing", "Balance", "10", Variations.warrior),
	new Pose("Warrior II", require("../assets/poses/WarriorBPose.png"), "Beginner", "Standing", "Balance", "10", Variations.warrior),
	new Pose("Warrior III", require("../assets/poses/WarriorCPose.png"), "Advanced", "Standing", "Balance", "10", Variations.warrior),
	new Pose("Wide-legged Bend I", require("../assets/poses/WideLeggedBend1Pose.png"), "Intermediate", "Standing", "Forward Bend", "10", Variations.wideLeggedBend),
	new Pose("Wide-legged Bend III", require("../assets/poses/WideLeggedBend3Pose.png"), "Intermediate", "Standing", "Forward Bend", "10", Variations.wideLeggedBend),
	new Pose("Wide Splits", require("../assets/poses/WideSplitsPose.png"), "Advanced", "Seated", "Balance", "10"),
	new Pose("Wind Removing", require("../assets/poses/WindRemovingPose.png"), "Beginner", "Supine", "Forward Bend", "10"),
]

export default Poses


const Difficulty = {
	"Beginner": 1,
	"Intermediate": 2,
	"Advanced": 3,
}

const Positions = {
	"Standing": 1,
	"Seated": 2,
	"Supine": 3,
	"Prone": 4,
	"Arm Balance": 5,
	"Supported": 6,
}

const Posture = {
	"Back Bend": 1,
	"Forward Bend": 2,
	"Lateral Bend": 3,
	"Twist": 4,
	"Balance": 5,
	"Neutral": 6,
}
