# Generated by Django 5.1.2 on 2024-11-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_thing_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='thing',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
    ]
